-- Q1. What are the details of all cars purchased in the year 2022?

SELECT make,type,style,cost_$,purchase_date
from cars c
join sales s
using(car_id)
WHERE purchase_date >= '2022-01-01' AND purchase_date < '2023-01-01'
order by purchase_date;

-- Q2. What is the total number of cars sold by each salesperson?
select 
salesman_id,
ss.name,
count(ss.name)as car__sold
from sales s
join salespersons ss
using(salesman_id)
group by ss.name,salesman_id
-- Q3. What is the total revenue generated by each salesperson?
select 
ss.name,
sum(cost_$) as sales,
salesman_id
from sales s
join salespersons ss
using(salesman_id)
join cars
using (car_id)
group by ss.name,salesman_id
order by sales desc
-- Q4. What are the details of the cars sold by each salesperson?
select
ss.name,car_id,make,type,style,
cost_$
from sales s
join salespersons ss
using(salesman_id)
join cars
using (car_id)
-- Q5. What is the total revenue generated by each car type?
select type ,sum(cost_$) as total_sales,s.car_id
from cars
join sales s
using(car_id)
group by type,s.car_id
order by total_sales desc
 -- Q6. What are the details of the cars sold in the year 2021 by 
-- salesperson 'Emily Wong'?
select make,type,style,cost_$,purchase_date,name
from cars c
join sales s
using (car_id)
join salespersons sp
using(salesman_id)
where name = 'Emily Wong' and purchase_date > '2020-12-31' and purchase_date < '2022-01-01'
-- Q7. What is the total revenue generated by the sales of hatchback cars?
select sum(cost_$),
type,style
from cars
join sales
using(car_id)
where style = 'hatchback'
group by type,style
-- Q8. What is the total revenue generated by the sales of SUV cars in 
-- the year 2022?
select sum(cost_$),
style
from cars
join sales
using(car_id)
where style = 'SUV'  and purchase_date > '2021-12-31' and purchase_date < '2023-01-01'
group by style
-- Q9. What is the name and city of the salesperson who sold the most 
-- number of cars in the year 2023?
select sum(cost_$) as s, s.name,s.city,
count(ss.car_id) as number_of_cars
from cars c
join sales ss
using(car_id)
join salespersons s
using(salesman_id)
where purchase_date > '2022-12-31' and purchase_date < '2024-01-01'
group by s.name,s.city
order by s desc
-- Q10. What is the name and age of the salesperson who generated the 
-- highest revenue in the year 2022?
select sum(cost_$) as s, s.name,s.age
from cars c
join sales ss
using(car_id)
join salespersons s
using(salesman_id)
where purchase_date > '2021-12-31' and purchase_date < '2023-01-01'
group by s.name,s.age
order by s desc





